# netlify.toml

[build]
  # this is the dir that will be published
  publish = "dist/"
  # command to setup your SSR environment
  command = "npm run generate"
[build.environment]
  NASA_API_KEY = "UJRYxzCtuIEhbcaGKGYCCFylEeGr7ITTKCBz8AfE"
  NASA_BASE_URL = "https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos"